os: windows
language: node_js
node_js:
  - 18
cache: npm
script:
  - npm run test:ci
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
notifications:
  webhooks: https://coveralls.io/webhook
