os: ubuntu-latest
language: node_js
node_js:
  - 18
cache: npm
before_install:
  - npm update
install:
  - npm install
  - npm run build
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
