language: node_js
sudo: false
notifications:
  email: false
node_js:
  - 12
  - 10
  - 8
before_script:
  - npm install
script:
  - npm run test:ci
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local-dir: docs/build/solution.js
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master
    - develop
