language: node_js
sudo: false
notifications:
  email: false
node_js:
- '10'
- '11'
cache: npm
script:
- npm run test:ci
- codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local-dir: docs/build/solutions.js
  target_branch: gh-pages
before_deploy:
- npm run docs:build
env:
- MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master
