name: Linting
on: push
jobs:
  STEPS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 100
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - name: Install Node.js dependencies
        run: npm ci --ignore-scripts
      - name: lint
        shell: bash
        run: |
          npx eslint . --ext .ts

