name: PR Tests

# Only run on non-draft PRs, and when PRs are synched
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    # Dont run if it's just markdown or doc files
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "guides/**"
      - "scripts/**"
      - "support/**"
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [21]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test in Chrome
        run: npm run test:chrome:ci

      - uses: codecov/codecov-action@v4
        with:
          directory: ./coverage
